# Generated by Django 6.0.3 on 2026-03-18 23:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentalHealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('q1_interest', models.IntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Little interest or pleasure in doing things')),
                ('q2_depressed', models.IntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Feeling down, depressed, or hopeless')),
                ('q3_sleep', models.IntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Trouble falling or staying asleep, or sleeping too much')),
                ('q4_tired', models.IntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Feeling tired or having little energy')),
                ('q5_appetite', models.IntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Poor appetite or overeating')),
                ('q6_failure', models.IntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Feeling bad about yourself')),
                ('q7_focus', models.IntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Trouble concentrating on things')),
                ('q8_movement', models.IntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Moving or speaking slowly, or being fidgety/restless')),
                ('q9_selfharm', models.IntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half the days'), (3, 'Nearly every day')], default=0, verbose_name='Thoughts that you would be better off dead')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mental_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WellnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sleep', 'Sleep'), ('exercise', 'Exercise'), ('water', 'Hydration'), ('diet', 'Nutrition'), ('mental', 'Mental Health'), ('medical', 'Medical'), ('other', 'Other')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['is_achieved', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WellnessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('mood', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Okay'), (2, 'Low'), (1, 'Very Low')])),
                ('stress_level', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')])),
                ('sleep_hours', models.CharField(choices=[('lt4', 'Less than 4 hours'), ('4to6', '4 – 6 hours'), ('6to8', '6 – 8 hours'), ('gt8', 'More than 8 hours')], max_length=10)),
                ('physical_activity', models.CharField(choices=[('none', 'None'), ('light', 'Light (walk, stretch)'), ('moderate', 'Moderate (30+ min exercise)'), ('intense', 'Intense (gym, sport, run)')], default='none', max_length=10)),
                ('appetite', models.CharField(choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('very_good', 'Very Good')], default='good', max_length=10)),
                ('has_headache', models.BooleanField(default=False, verbose_name='Headache')),
                ('has_fever', models.BooleanField(default=False, verbose_name='Fever')),
                ('has_fatigue', models.BooleanField(default=False, verbose_name='Fatigue / Tiredness')),
                ('has_nausea', models.BooleanField(default=False, verbose_name='Nausea')),
                ('has_anxiety', models.BooleanField(default=False, verbose_name='Anxiety')),
                ('has_pain', models.BooleanField(default=False, verbose_name='Body Pain')),
                ('other_symptoms', models.CharField(blank=True, max_length=200, verbose_name='Other Symptoms')),
                ('notes', models.TextField(blank=True, help_text='Optional — describe your day in a few words', verbose_name='How are you feeling today?')),
                ('water_glasses', models.PositiveIntegerField(default=0, help_text='1 glass ≈ 250 ml', verbose_name='Glasses of water today')),
                ('meals_today', models.PositiveIntegerField(default=3, verbose_name='Number of meals eaten today')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='wellness_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
