# Generated by Django 6.0.3 on 2026-03-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['-is_primary', 'name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='alt_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Alternative Phone'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_medications',
            field=models.TextField(blank=True, help_text='List any medication you take regularly', verbose_name='Current Medications'),
        ),
        migrations.AddField(
            model_name='user',
            name='disability',
            field=models.CharField(blank=True, help_text='Any physical or learning disability we should know about', max_length=200, verbose_name='Disability / Special Needs'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, max_length=150, verbose_name='Faculty / College'),
        ),
        migrations.AddField(
            model_name='user',
            name='genotype',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS'), ('SC', 'SC'), ('CC', 'CC'), ('unknown', 'Unknown')], default='unknown', max_length=8, verbose_name='Genotype'),
        ),
        migrations.AddField(
            model_name='user',
            name='hall_of_residence',
            field=models.CharField(blank=True, help_text='Leave blank if you live off-campus', max_length=150, verbose_name='Hall of Residence'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_nhis',
            field=models.BooleanField(default=False, verbose_name='Has NHIS card?'),
        ),
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Height (cm)'),
        ),
        migrations.AddField(
            model_name='user',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('unknown', 'Unknown / Not tested')], max_length=20, verbose_name='HIV Status (confidential)'),
        ),
        migrations.AddField(
            model_name='user',
            name='immunization_up_to_date',
            field=models.BooleanField(default=False, verbose_name='Immunisations up to date?'),
        ),
        migrations.AddField(
            model_name='user',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, verbose_name='Other Insurance Provider'),
        ),
        migrations.AddField(
            model_name='user',
            name='matric_number',
            field=models.CharField(blank=True, help_text='Your official university matriculation number', max_length=20, null=True, unique=True, verbose_name='Matric Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, default='Nigerian', max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='nhis_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='NHIS Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='past_surgeries',
            field=models.TextField(blank=True, help_text='Include year and reason if possible', verbose_name='Past Surgeries / Hospitalisations'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='state_of_origin',
            field=models.CharField(blank=True, choices=[('Abia', 'Abia'), ('Adamawa', 'Adamawa'), ('Akwa Ibom', 'Akwa Ibom'), ('Anambra', 'Anambra'), ('Bauchi', 'Bauchi'), ('Bayelsa', 'Bayelsa'), ('Benue', 'Benue'), ('Borno', 'Borno'), ('Cross River', 'Cross River'), ('Delta', 'Delta'), ('Ebonyi', 'Ebonyi'), ('Edo', 'Edo'), ('Ekiti', 'Ekiti'), ('Enugu', 'Enugu'), ('FCT', 'FCT - Abuja'), ('Gombe', 'Gombe'), ('Imo', 'Imo'), ('Jigawa', 'Jigawa'), ('Kaduna', 'Kaduna'), ('Kano', 'Kano'), ('Katsina', 'Katsina'), ('Kebbi', 'Kebbi'), ('Kogi', 'Kogi'), ('Kwara', 'Kwara'), ('Lagos', 'Lagos'), ('Nasarawa', 'Nasarawa'), ('Niger', 'Niger'), ('Ogun', 'Ogun'), ('Ondo', 'Ondo'), ('Osun', 'Osun'), ('Oyo', 'Oyo'), ('Plateau', 'Plateau'), ('Rivers', 'Rivers'), ('Sokoto', 'Sokoto'), ('Taraba', 'Taraba'), ('Yobe', 'Yobe'), ('Zamfara', 'Zamfara')], max_length=30, verbose_name='State of Origin'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Weight (kg)'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary contact?'),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='relationship',
            field=models.CharField(choices=[('parent', 'Parent'), ('sibling', 'Sibling'), ('spouse', 'Spouse / Partner'), ('guardian', 'Guardian'), ('relative', 'Other Relative'), ('friend', 'Friend')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=models.TextField(blank=True, help_text='e.g. Penicillin, peanuts, latex — write "None" if none', verbose_name='Known Allergies'),
        ),
        migrations.AlterField(
            model_name='user',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=8, verbose_name='Blood Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='e.g. Asthma, diabetes, epilepsy — write "None" if none', verbose_name='Chronic Conditions / Disabilities'),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=150, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other / Prefer not to say')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Currently available for appointments?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('500', '500 Level'), ('600', '600 Level'), ('PGD', 'PGD'), ('MSC', 'M.Sc'), ('PHD', 'Ph.D')], max_length=5, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=250, verbose_name='Qualifications'),
        ),
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=150, verbose_name='Specialization / Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Staff ID'),
        ),
    ]
