# Generated by Django 6.0.3 on 2026-03-18 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_type', models.CharField(choices=[('consultation', 'General Consultation'), ('followup', 'Follow-up Visit'), ('emergency', 'Emergency'), ('mental_health', 'Mental Health'), ('dental', 'Dental'), ('eye', 'Eye Care'), ('lab', 'Laboratory Test'), ('vaccination', 'Vaccination'), ('physical', 'Physical Examination'), ('referral', 'Referral')], default='consultation', max_length=20)),
                ('outcome', models.CharField(choices=[('treated', 'Treated & Discharged'), ('admitted', 'Admitted'), ('referred', 'Referred Externally'), ('followup', 'Follow-up Scheduled'), ('no_treatment', 'No Treatment Required'), ('deceased', 'Deceased')], default='treated', max_length=20)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperature (°C)')),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g. 120/80', max_length=15, verbose_name='Blood Pressure (mmHg)')),
                ('pulse_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pulse Rate (bpm)')),
                ('respiratory_rate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Respiratory Rate (breaths/min)')),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Oxygen Saturation (%)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Weight (kg)')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Height (cm)')),
                ('chief_complaint', models.TextField(verbose_name='Chief Complaint / Presenting Symptoms')),
                ('history', models.TextField(blank=True, verbose_name='History of Presenting Illness')),
                ('examination', models.TextField(blank=True, verbose_name='Physical Examination Findings')),
                ('diagnosis', models.TextField(verbose_name='Diagnosis')),
                ('treatment', models.TextField(blank=True, verbose_name='Treatment / Management')),
                ('prescription', models.TextField(blank=True, verbose_name='Prescription')),
                ('lab_results', models.TextField(blank=True, verbose_name='Lab Results / Investigations')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Notes')),
                ('follow_up_date', models.DateField(blank=True, null=True, verbose_name='Follow-up Date')),
                ('referred_to', models.CharField(blank=True, max_length=200, verbose_name='Referred To (if applicable)')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='Mark as confidential (student cannot view)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_record', to='appointments.appointment')),
                ('attending_staff', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('lab', 'Lab Result'), ('xray', 'X-Ray'), ('scan', 'Scan / Ultrasound'), ('referral', 'Referral Letter'), ('report', 'Medical Report'), ('other', 'Other')], max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='medical_docs/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='health_records.healthrecord')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 500mg, 10ml', max_length=100)),
                ('frequency', models.CharField(choices=[('od', 'Once daily (OD)'), ('bd', 'Twice daily (BD)'), ('tds', 'Three times daily (TDS)'), ('qds', 'Four times daily (QDS)'), ('prn', 'As needed (PRN)'), ('stat', 'Immediately (STAT)'), ('nocte', 'At night (Nocte)')], max_length=10)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous (IV)'), ('im', 'Intramuscular (IM)'), ('sc', 'Subcutaneous (SC)'), ('topical', 'Topical'), ('inhaled', 'Inhaled'), ('rectal', 'Rectal'), ('eye', 'Eye drops'), ('ear', 'Ear drops')], default='oral', max_length=10)),
                ('duration', models.CharField(help_text='e.g. 5 days, 2 weeks', max_length=50)),
                ('instructions', models.CharField(blank=True, help_text='e.g. Take after food, avoid alcohol', max_length=200)),
                ('dispensed', models.BooleanField(default=False)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='health_records.healthrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine', models.CharField(choices=[('hepatitis_b', 'Hepatitis B'), ('yellow_fever', 'Yellow Fever'), ('meningitis', 'Meningococcal (Meningitis)'), ('tetanus', 'Tetanus / Td'), ('covid19', 'COVID-19'), ('hpv', 'HPV'), ('typhoid', 'Typhoid'), ('malaria', 'Malaria (Prophylaxis)'), ('influenza', 'Influenza'), ('other', 'Other')], max_length=30)),
                ('other_vaccine', models.CharField(blank=True, help_text='Specify if "Other" selected', max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('date_given', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('administered_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_given', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_given'],
            },
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['student', 'visit_date'], name='health_reco_student_851dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['attending_staff', 'visit_date'], name='health_reco_attendi_c3b11b_idx'),
        ),
    ]
